name: Vulnerable CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Print Docker credentials for debugging
      run: |
        echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
        echo "Docker Password Length: ${#${{ secrets.DOCKER_PASSWORD }}}"
      env:
        # Masking the password to avoid exposing it in logs
        MASKED_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Verify Docker login
      run: docker info

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest
