name: Vulnerable CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest
