name: Vulnerable CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Print Docker credentials for debugging
      run: |
        echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
        echo "Docker Password Length: ${#${{ secrets.DOCKER_PASSWORD }}}"

    - name: Validate Docker credentials
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is not set"
          exit 1
        fi
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD is not set"
          exit 1
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      id: docker-login

    - name: Check Docker login result
      if: steps.docker-login.outcome != 'success'
      run: |
        echo "Docker login failed"
        exit 1

    - name: Verify Docker login
      run: docker info

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/vulnerable-app:latest
