name: Vulnerable CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "defconcv32@gmail.com"  # Replace with your Docker username
        password: "Lasvegas@32"  # Replace with your Docker password

    - name: Build and push Docker image
      run: |
        docker build -t vuln01/vulnerable-app:latest .
        docker push vuln01/vulnerable-app:latest

    - name: Introduce artifact poisoning
      run: |
        echo "Introducing malicious code into the Docker image..."
        echo "This code will be executed when the image is run..." >> Dockerfile
        docker build -t vuln01/vulnerable-app:latest .
        docker push vuln01/vulnerable-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Docker image
      run: |
        docker pull vuln01/vulnerable-app:latest
        docker run -d -p 80:80 vuln01/vulnerable-app:latest
